FROM mosaiksoftware/debian
#
# PHP Farm Docker image
#

MAINTAINER Christian Holzberger, ch@mosaiksoftware.de

ENV PHP_VERSION 5.5.34
ENV PHPMYADMIN_VERSION 4.6.0

COPY config /etc
COPY selections /selections
# add hhvm key
ENV DEBIAN_FRONTEND noninteractive
# make php 5.3 work again
ENV LDFLAGS "-lssl -lcrypto"
RUN apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449
# add some build tools
RUN begin-apt && \
			apt-get install -y ca-certificates && \
    	set-selections phpfarm-basic && \
			set-selections phpfarm-dev && \
			apt-get build-dep -y php5 && \
		end-apt

#freetype build fix
RUN mkdir /usr/include/freetype2/freetype/ && ln -s /usr/include/freetype2/freetype.h /usr/include/freetype2/freetype/freetype.h
RUN git clone https://github.com/cweiske/phpfarm.git /phpfarm 

# add customized configuration
COPY config/phpfarm /phpfarm/src
# install and run the phpfarm script
# compile, then delete sources (saves space)
#set short_open_tag
VOLUME /pkg
COPY buildphpfarm.sh /buildphpfarm.sh
ENTRYPOINT ["/bin/bash"]
CMD ["/buildphpfarm.sh"]
