[template]
src = "php-base.ini"
dest = "/etc/php/conf.d/php-base.ini"

keys = [
	"/php/date/timezone",
	"/php/log_errors",
	"/php/display_errors",
	"/php/error_reporting",
	"/php/post_max_size",
	"/php/upload_max_filesize",
	"/php/max_file_uploads"
]
