[template]
src = "ssmtp.conf.tmpl"
dest = "/etc/ssmtp/ssmtp.conf"

keys = [
	"/ssmtp/root",
	"/ssmtp/mailhub",
	"/ssmtp/hostname",
	"/ssmtp/fromlineoverride",
	"/ssmtp/authuser",
	"/ssmtp/authpass"
]
