[template]
src = "php-base.ini.tmpl"
dest = "/etc/php5/fpm/conf.d/30-php-base.ini"

keys = [
	"/php/date/timezone",
	"/php/log/errors",
	"/php/display/errors",
	"/php/error/reporting",
	"/php/post/max_size",
	"/php/upload/max/filesize",
	"/php/max/file/uploads",
	"/php/memory/limit",
	"/php/max/execution/time",
	"/php/max/input/time",
	"/php/short/open/tag"
]
